#!/bin/bash
set -e

# Determine web user and folder
webuser=$(ps aux | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1)
if [ -d "/srv/www" ]; then
  webdir="/srv/www"
elif [ -d "/var/www" ]; then
  webdir="/var/www"
else
  echo "No web folder found."
  exit 1
fi

# Drop database on purge
if [ "$1" = "purge" ]; then
  rm -rf ${webdir}/501
  mariadb -e "
  DROP USER IF EXISTS 'blog_db_user'@'localhost';
  DROP DATABASE IF EXISTS blog_db;
  FLUSH PRIVILEGES;"
fi